REM Build Bat File
REM Precheck the Resource 
"C:\Program Files\MRE SDK V3.0.00\tools\ResEditor\CmdShell.exe" save  "D:\MyGitHub\Mrecp\Mrecp.vcproj"
REM Copmile c file 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -c -fpic -g -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -o "D:\MyGitHub\Mrecp\arm\gccmain.o" -c "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\src\gccmain.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files\MRE SDK V3.0.00\include" -I "C:\Program Files\MRE SDK V3.0.00\include\service" -I "D:\MyGitHub\Mrecp\include" -I "D:\MyGitHub\Mrecp\include\service" -I "D:\MyGitHub\Mrecp\include\component" -I "D:\MyGitHub\Mrecp\ResID" -I "D:\MyGitHub\Mrecp\src\app\widget" -I "D:\MyGitHub\Mrecp\src\app\launcher" -I "D:\MyGitHub\Mrecp\src\app\wallpaper" -I "D:\MyGitHub\Mrecp\src\app\screen_lock" -I "D:\MyGitHub\Mrecp\include\service" -I "D:\MyGitHub\Mrecp\include\component" -I "D:\MyGitHub\Mrecp\include\service" -I "D:\MyGitHub\Mrecp\src\framework" -I "D:\MyGitHub\Mrecp\src\framework\ui_core\base" -I "D:\MyGitHub\Mrecp\src\framework\ui_core\mvc" -I "D:\MyGitHub\Mrecp\src\framework\ui_core\pme" -I "D:\MyGitHub\Mrecp\src\framework\mmi_core" -I "D:\MyGitHub\Mrecp\src\ui_engine\vrt\interface" -I "D:\MyGitHub\Mrecp\src\component" -I "D:\MyGitHub\Mrecp\src\ui_engine\framework\xml" -I "D:\MyGitHub\Mrecp"
REM Copmile c file 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-g++" -c -fpic -g -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -fno-rtti -fcheck-new -o "D:\MyGitHub\Mrecp\arm\Console.o" -c "d:\MyGitHub\Mrecp\Console.cpp"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files\MRE SDK V3.0.00\include" -I "C:\Program Files\MRE SDK V3.0.00\include\service" -I "D:\MyGitHub\Mrecp\include" -I "D:\MyGitHub\Mrecp\include\service" -I "D:\MyGitHub\Mrecp\include\component" -I "D:\MyGitHub\Mrecp\ResID" -I "D:\MyGitHub\Mrecp\src\app\widget" -I "D:\MyGitHub\Mrecp\src\app\launcher" -I "D:\MyGitHub\Mrecp\src\app\wallpaper" -I "D:\MyGitHub\Mrecp\src\app\screen_lock" -I "D:\MyGitHub\Mrecp\include\service" -I "D:\MyGitHub\Mrecp\include\component" -I "D:\MyGitHub\Mrecp\include\service" -I "D:\MyGitHub\Mrecp\src\framework" -I "D:\MyGitHub\Mrecp\src\framework\ui_core\base" -I "D:\MyGitHub\Mrecp\src\framework\ui_core\mvc" -I "D:\MyGitHub\Mrecp\src\framework\ui_core\pme" -I "D:\MyGitHub\Mrecp\src\framework\mmi_core" -I "D:\MyGitHub\Mrecp\src\ui_engine\vrt\interface" -I "D:\MyGitHub\Mrecp\src\component" -I "D:\MyGitHub\Mrecp\src\ui_engine\framework\xml" -I "D:\MyGitHub\Mrecp"
REM Copmile c file 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-g++" -c -fpic -g -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -fno-rtti -fcheck-new -fno-rtti -fcheck-new -o "D:\MyGitHub\Mrecp\arm\Console_io.o" -c "d:\MyGitHub\Mrecp\Console_io.cpp"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files\MRE SDK V3.0.00\include" -I "C:\Program Files\MRE SDK V3.0.00\include\service" -I "D:\MyGitHub\Mrecp\include" -I "D:\MyGitHub\Mrecp\include\service" -I "D:\MyGitHub\Mrecp\include\component" -I "D:\MyGitHub\Mrecp\ResID" -I "D:\MyGitHub\Mrecp\src\app\widget" -I "D:\MyGitHub\Mrecp\src\app\launcher" -I "D:\MyGitHub\Mrecp\src\app\wallpaper" -I "D:\MyGitHub\Mrecp\src\app\screen_lock" -I "D:\MyGitHub\Mrecp\include\service" -I "D:\MyGitHub\Mrecp\include\component" -I "D:\MyGitHub\Mrecp\include\service" -I "D:\MyGitHub\Mrecp\src\framework" -I "D:\MyGitHub\Mrecp\src\framework\ui_core\base" -I "D:\MyGitHub\Mrecp\src\framework\ui_core\mvc" -I "D:\MyGitHub\Mrecp\src\framework\ui_core\pme" -I "D:\MyGitHub\Mrecp\src\framework\mmi_core" -I "D:\MyGitHub\Mrecp\src\ui_engine\vrt\interface" -I "D:\MyGitHub\Mrecp\src\component" -I "D:\MyGitHub\Mrecp\src\ui_engine\framework\xml" -I "D:\MyGitHub\Mrecp"
REM Copmile c file 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-g++" -c -fpic -g -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -fno-rtti -fcheck-new -fno-rtti -fcheck-new -fno-rtti -fcheck-new -o "D:\MyGitHub\Mrecp\arm\main.o" -c "d:\MyGitHub\Mrecp\main.cpp"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files\MRE SDK V3.0.00\include" -I "C:\Program Files\MRE SDK V3.0.00\include\service" -I "D:\MyGitHub\Mrecp\include" -I "D:\MyGitHub\Mrecp\include\service" -I "D:\MyGitHub\Mrecp\include\component" -I "D:\MyGitHub\Mrecp\ResID" -I "D:\MyGitHub\Mrecp\src\app\widget" -I "D:\MyGitHub\Mrecp\src\app\launcher" -I "D:\MyGitHub\Mrecp\src\app\wallpaper" -I "D:\MyGitHub\Mrecp\src\app\screen_lock" -I "D:\MyGitHub\Mrecp\include\service" -I "D:\MyGitHub\Mrecp\include\component" -I "D:\MyGitHub\Mrecp\include\service" -I "D:\MyGitHub\Mrecp\src\framework" -I "D:\MyGitHub\Mrecp\src\framework\ui_core\base" -I "D:\MyGitHub\Mrecp\src\framework\ui_core\mvc" -I "D:\MyGitHub\Mrecp\src\framework\ui_core\pme" -I "D:\MyGitHub\Mrecp\src\framework\mmi_core" -I "D:\MyGitHub\Mrecp\src\ui_engine\vrt\interface" -I "D:\MyGitHub\Mrecp\src\component" -I "D:\MyGitHub\Mrecp\src\ui_engine\framework\xml" -I "D:\MyGitHub\Mrecp"
REM Copmile c file 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-g++" -c -fpic -g -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -fno-rtti -fcheck-new -fno-rtti -fcheck-new -fno-rtti -fcheck-new -fno-rtti -fcheck-new -o "D:\MyGitHub\Mrecp\arm\T2Input.o" -c "d:\MyGitHub\Mrecp\T2Input.cpp"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files\MRE SDK V3.0.00\include" -I "C:\Program Files\MRE SDK V3.0.00\include\service" -I "D:\MyGitHub\Mrecp\include" -I "D:\MyGitHub\Mrecp\include\service" -I "D:\MyGitHub\Mrecp\include\component" -I "D:\MyGitHub\Mrecp\ResID" -I "D:\MyGitHub\Mrecp\src\app\widget" -I "D:\MyGitHub\Mrecp\src\app\launcher" -I "D:\MyGitHub\Mrecp\src\app\wallpaper" -I "D:\MyGitHub\Mrecp\src\app\screen_lock" -I "D:\MyGitHub\Mrecp\include\service" -I "D:\MyGitHub\Mrecp\include\component" -I "D:\MyGitHub\Mrecp\include\service" -I "D:\MyGitHub\Mrecp\src\framework" -I "D:\MyGitHub\Mrecp\src\framework\ui_core\base" -I "D:\MyGitHub\Mrecp\src\framework\ui_core\mvc" -I "D:\MyGitHub\Mrecp\src\framework\ui_core\pme" -I "D:\MyGitHub\Mrecp\src\framework\mmi_core" -I "D:\MyGitHub\Mrecp\src\ui_engine\vrt\interface" -I "D:\MyGitHub\Mrecp\src\component" -I "D:\MyGitHub\Mrecp\src\ui_engine\framework\xml" -I "D:\MyGitHub\Mrecp"
REM Link app 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -o "D:\MyGitHub\Mrecp\Mrecp.axf"  "D:\MyGitHub\Mrecp\arm\gccmain.o"  "D:\MyGitHub\Mrecp\arm\Console.o"  "D:\MyGitHub\Mrecp\arm\Console_io.o"  "D:\MyGitHub\Mrecp\arm\main.o"  "D:\MyGitHub\Mrecp\arm\T2Input.o" -fpic -msvr4-struct-return -pie  -T "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc\scat.ld" -l:"C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc\percommon.a" -l:"C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc\peraudio.a" -l:"C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc\perfile.a" -l:"C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc\persim.a" -l:"C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc\persec.a" -l:"C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc\persysstorage.a" -l:"C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc\persysfile.a"
REM Pack resource to app 
"C:\Program Files\MRE SDK V3.0.00\tools\ResEditor\CmdShell.exe" pack -silent -resolution 240x320 -o "D:\MyGitHub\Mrecp\Mrecp.pkd" -e AXF "D:\MyGitHub\Mrecp\Mrecp.vcproj" "D:\MyGitHub\Mrecp\Mrecp.axf"
REM Add tag infromation 
"C:\Program Files\MRE SDK V3.0.00\tools\PackDigist.exe" "D:\MyGitHub\Mrecp\Mrecp.vcproj" "Mrecp" "0.1.0" "RDZDX" "1500" "NotSupportBg" "Not Support rotate" "Mrecp" "Mrecp" "Mrecp" "9246012102087182" "content" " Audio File SIM card Sec SysStorage SysFile" "vxp" "GCC" "PKD" "UnCompress" "NoVPI" "Adaptable" "15728960" "UnSysMemAble" "
    " "-1" "UNPUSH" "-1" ""  "UnAutoStart"  "UnTransferImg" "NoIdleShortcut"  D:\MyGitHub\Mrecp\arm D:\MyGitHub\Mrecp\build.log

